export const beginMatrix: Record<string, string[]> = {
  "what": ["even is", "are", "do I"],
  "why": ["my", "cant", "r", "dont","AM I" ],
  "I": ["HAVE", "have", "cannot believe", "am", "ate", "will"],
  "My": ["enemies have", "kitty", "mommy", "butt", "body"],
  "how": ["DO I","am I","will I","can I"],
  
  "even is": [ "Hunter Biden","drowning","womankind","hedgehogs","an android user","WeTwerk","criss","stefan-boltzmann","frontogenesis","the right-hand rule"],
  "will I": ["ever","solve"],
  "do I": ["love"],
  "are": ["you","babies","we"],
  "my": ["tummy hairy", "butt hurt","feet smell","finger dirty"],
  "DO I": [ "HAVE", "need", "have"],
  "cant": ["my kiddy play with me","i stop PEEING","u mind you're own business?","I GO to Home Goods"],
  "r": ["you not gay","there bones in my basement","u BOTHERING ME"],
  "dont": ["I get smooches","plants poop","job"],
  "HAVE": ["TO GO TO WORK, kill me", "NO BABES","to go potty", "to"],
  "have": ["a","TOO MUCH HUNGER","to work"],
  "cannot believe": ["old man boss wont","people over 30 arent illegal","how u all are so old","KIDDY WONT PLAY WITH ME","Dangling was right about aliens"],
  "am": ["gayer than Adrenal","Beyonce irl","Tiger Woods irl","Jeffery BEZOS irl","THE DEEP STATE","tired of seeing they're FACE"],
  "am I": ["going to smooch Adrenal","DONE LOGGING","dying","not rich YET"],
  "ate": ["dinner ama","POISON","26.75 calories today ama","my kittys food","$100 of mcdonalds ama"],
  "will": ["commit an act of terrorism","not let my enemies poison me","NOT believe you're lies","rip you’re flesh asunder"],
  "enemies have": ["taken me to HomeGoods","POISONED ME","left the dryer FULL","given me smooches"],
  "kitty": ["will","is cute","plotting to kill me"],
  "mommy": ["wont give me MY MONEY","says I have to have family dinner, KILL ME", "is calling me"],
  "butt": ["wont stop shidding","wont stop leaking","HURTS","too big"],
  "body": ["is sore","is a machine","BMI is < 20","wont stop BLEEDING"],
  "can I": ["make","get","solve"],
  "AM I": ["LOSING MY", "not eating", "still", "NEVER"],
  
  "ever": ["love","need","smooch","get a sexy babe"],
  "solve": ["MY HUNGER","world hunger","the Middle East conflict","Josh's single life"],
  "to": ["wash", "eat", "obey"],
  "wash": ["my dingle", "my ANUS", "MY SHEETS"],
  "eat": ["calories", "VEGETABLES"],
  "obey": ["international law", "the CONSTITUTION", "MY KIDDY"],
  "get a sexy babe": ["on my"],
  "love": ["more than","less than"],
  "more than": ["KITTY","wings","WET BEEF"],
  "less than": ["Sepist","BANATEE","woat takes"],
  "you": ["LOOKING AT","THINKING","doing rn"],
  "we": ["doing to solve world hunger","thinking","shidding"],
  "need": ["oxygen","money","FOOD","to pay taxes","Juul pods"],
  "job": ["give me more money?","have remote work","make me drive CLOSER TO HOME"],  
  "a": ["growth","PROBLEM","big"],
  "growth": ["on my","that wont"],
  "on my": ["fingy","kiddy","balls","tummy","Juul pod"],
  "big": ["butt"],
  "that wont": ["quit","stop oozing","stop mocking me"],
  "old man boss wont": ["buy me","leave ME ALONE","smooch","take me to HOME GOODS"],
  "smooch": ["ME","josh","Adrenal","kiddy"],
  "buy me": ["sushi","chicken wings","a house","new kitty","Juul pods"],
  "make": ["my family", "alcohol", "drugs"],
  "my family": ["give ME MORE MONEY","to stop scamming me","give me they're house"],
  "alcohol": ["illegal"],
  "get": ["Sepist", "Zeph", "PMChem","Dangling"],
  "Sepist": ["to hire me","to stop talking","banned"],
  "Zeph": ["to date my mommy","to fix my brakes","a new hair color"],
  "PMChem": ["to STOP IGNORING ME", "to run my retirement account"],
  "Dangling": ["to take me to a strip club","out of OHIO"],
  "LOSING MY": ["RELIGION", "food stamps!", "MIND", "keys"],
  "not eating": ["wet beef sammie", "CHICKIE WINGS", "bbq", "LEAN HOGS"],
  "still": ["ALIVE", "HERE LORDE", "not eating", "SO COLD"],
  "NEVER": ["DONE WORKING", "sleeping", "able to take a normal SHID"],
};