export const beginMatrix: Record<string, string[]> = {
  "what": ["even is", "are", "do I"],
  "why": ["my", "DO I", "cant", "r", "dont" ],
  "I": ["HAVE", "have", "cannot believe", "am", "ate", "will"],
  "My": ["enemies have", "kitty", "mommy", "butt", "body"],
  "how": ["DO I","am I","will I"],
  
  "even is": [ "Hunter Biden","drowning","womankind","hedgehogs","an android user","WeTwerk","criss","stefan-boltzmann","frontogenesis","the right-hand rule"],
  "will I": ["ever","solve"],
  "do I": ["love"],
  "are": ["you","babies","we"],
  "my": ["tummy hairy", "butt hurt","feet smell","finger dirty"],
  "DO I": [ "HAVE", "need", "have"],
  "cant": ["my kiddy play with me","i stop PEEING","u mind you're own business?","I GO to Home Goods"],
  "r": ["you not gay","there bones in my basement","u BOTHERING ME"],
  "dont": ["I get smooches","plants poop","job"],
  "HAVE": ["TO GO TO WORK, kill me", "NO BABES","to go potty"],
  "have": ["a","TOO MUCH HUNGER","to work"],
  "cannot believe": ["old man boss wont","people over 30 arent illegal","how u all are so old","KIDDY WONT PLAY WITH ME","Dangling was right about aliens"],
  "am": ["going to smooch Adrenal","DONE LOGGING","dying","Jeffery BEZOS irl"],
  "am I": ["going to smooch Adrenal","DONE LOGGING","dying","Jeffery BEZOS irl"],
  "ate": ["dinner ama","POISON","26.75 calories today ama","my kittys food","$100 of mcdonalds ama"],
  "will": ["commit an act of terrorism","not let my enemies poison me","NOT believe you're lies","rip you’re flesh asunder"],
  "enemies have": ["taken me to HomeGoods","POISONED ME","left the dryer FULL","given me smooches"],
  "kitty": ["will","is cute","plotting to kill me"],
  "mommy": ["wont give me MY MONEY","says I have to have family dinner, KILL ME", "is calling me"],
  "butt": ["wont stop shidding","wont stop leaking","HURTS","too big"],
  "body": ["is sore","is a machine"],
  
  "ever": ["love","need","smooch","get a sexy babe"],
  "solve": ["MY HUNGER","world hunger","the Middle East conflict","the Navier-Stokes equation"],
  "get a sexy babe": ["on my"],
  "love": ["more than","less than"],
  "more than": ["KITTY","wings","WET BEEF"],
  "less than": ["Sepist","BANATEE","woat takes"],
  "you": ["LOOKING AT","THINKING","doing rn"],
  "we": ["doing to solve world hunger","thinking","shidding"],
  "need": ["oxygen","money","FOOD","to pay taxes","Juul pods"],
  "job": ["give me more money?","have remote work","make me drive CLOSER TO HOME"],  
  "a": ["growth","PROBLEM","big"],
  "growth": ["on my","that wont"],
  "on my": ["fingy","kiddy","balls","tummy","Juul pod"],
  "big": ["butt"],
  "that wont": ["quit","stop oozing","stop mocking me"],
  "old man boss wont": ["buy me","leave ME ALONE","smooch","take me to HOME GOODS"],
  "smooch": ["ME","josh","Adrenal","kiddy"],
  "buy me": ["sushi","chicken wings","a house","new kitty","Juul pods"],
};