export const beginMatrix: Record<string, string[]> = {
  "what": ["even is", "are","do I"],
  "why": ["cant", "r","dont","AM I" ],
  "I": ["HAVE", "have", "cannot believe", "am", "ate", "will"],
  "My": ["enemies have", "mommy", "butt", "body"],
  "how": ["am I","can I"],
  
  "even is": [ "womankind","an android user","WeTwerk","mortgage points"],
  "will I": ["ever","solve"],
  "do I": ["love"],
  "are": ["you","we"],
  "my": ["tummy hairy","butt hurt","feet smell","finger dirty"],
  "cant": ["my kiddy play with me","i stop PEEING","u mind you're own business?","I OWN REAL ESTATE"],
  "r": ["you not gay","u BOTHERING ME"],
  "dont": ["I get smooches","plants poop","they accept MY OFFER"],
  "HAVE": ["TO GO TO WORK, kill me", "NO BABES","to"],
  "have": ["a"],
  "cannot believe": ["old man boss wont","people over 30 arent illegal","Dangling was right about aliens"],
  "am": ["gayer than Adrenal","Beyonce irl","Tiger Woods irl","Jeffery BEZOS irl","THE DEEP STATE","tired of seeing they're FACE"],
  "am I": ["going to smooch Adrenal","DONE LOGGING","dying","not rich YET"],
  "ate": ["dinner ama","POISON","26.75 calories today ama","my kittys food","$100 of mcdonalds ama"],
  "will": ["commit an act of terrorism","not let my enemies poison me","NOT believe you're lies","rip you’re flesh asunder"],
  "enemies have": ["outbid me on that house","POISONED ME","left the dryer FULL"],
  "mommy": ["wont give me MY MONEY","says I have to have family dinner, KILL ME"],
  "butt": ["wont stop shidding","HURTS","is WAY TOO BIG"],
  "body": ["is a machine","BMI is < 20","wont stop BLEEDING","has a GOAT bloodline"],
  "can I": ["get"],
  "AM I": ["LOSING MY", "still", "NEVER"],
  "is it even": ["meat","a pickle","a nipple"],
  
  "ever": ["BE LOVED","smooch","get a SEXY babe"],
  "solve": ["MY HUNGER","the Middle East conflict","Josh's single life"],
  "to": ["wash", "obey"],
  "wash": ["my dingle", "my ANUS", "MY SHEETS"],
  "obey": ["international law", "the CONSTITUTION", "MY KIDDY"],
  "get a sexy babe": ["on my"],
  "love": ["more than","less than"],
  "more than": ["KITTY","WET BEEF"],
  "less than": ["Sepist","BANATEE","my realtor"],
  "you": ["doing to HELP ME???","THINKING","doing rn"],
  "we": ["doing to solve world hunger","thinking","shidding"],
  "need": ["oxygen","money","FOOD","to pay taxes"],
  "job": ["give me more money?","have remote work","make me drive CLOSER TO HOME"],  
  "a": ["growth","PROBLEM","big"],
  "growth": ["on my"],
  "on my": ["fingy","balls","tummy"],
  "big": ["butt"],
  "that wont": ["quit","stop oozing","stop mocking me"],
  "old man boss wont": ["buy me","leave ME ALONE","smooch"],
  "smooch": ["ME","josh","Adrenal","kiddy"],
  "buy me": ["sushi","chicken wings","a house","new kitty","Juul pods"],
  "make": ["my family", "alcohol", "drugs"],
  "my family": ["give ME MORE MONEY","stop scamming me","give me they're house"],
  "alcohol": ["illegal"],
  "get": ["Sepist", "Zeph", "PMChem","Dangling"],
  "Sepist": ["to hire me","to stop talking","banned"],
  "Zeph": ["to date my mommy","to fix my brakes","get a new hair color"],
  "PMChem": ["to STOP IGNORING ME", "to run my retirement account"],
  "Dangling": ["to take me to a strip club","out of OHIO"],
  "LOSING MY": ["RELIGION", "food stamps!", "MIND"],
  "still": ["HERE LORDE", "SO COLD", "NOT A HOMEOWNER"],
  "NEVER": ["DONE WORKING", "able to take a normal SHID"],
  "meat": ["if it isnt wet","if I cant beat it"],
  "a pickle": ["if I cant hide it","if it isnt Dangling"],
  "a nipple": ["if its not pepperoni flavored", "if i cant milk it"],
};